services:
  angular-app:
    build: .
    restart: always
    ports:
      - "4200:4200"   # Asegúrate de que el puerto 80 esté expuesto
    container_name: pokemon-ssr
    networks:
      - angular-net

networks:
  angular-net:
    driver: bridge
